#!/usr/bin/env python3
"""
Copy ninja card PNG images from assets/ to docs/ninking/images/cards/
for GitHub Pages deployment.

The image files are NOT committed to git (docs/ninking/images/ is gitignored).
They are generated by this script in CI and pre-commit hook.
"""

import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "assets" / "images" / "cards" / "ninjas"
DST = REPO_ROOT / "docs" / "ninking" / "images" / "cards"


def main() -> None:
    if not SRC.exists():
        print(f"  ⚠  Source not found: {SRC}", file=sys.stderr)
        sys.exit(1)

    DST.mkdir(parents=True, exist_ok=True)

    count = 0
    for f in sorted(SRC.glob("*.png")):
        shutil.copy2(f, DST / f.name)
        count += 1

    print(f"  Copied {count} card images to {DST}", file=sys.stderr)


if __name__ == "__main__":
    main()
